from ex1 import HealingCreatureFactory, TransformCreatureFactory


if __name__ == "__main__":
    print("Testing Creature with healing capability")
    print(" base:")
    sproutling = HealingCreatureFactory().create_base()
    print(sproutling.describe())
    print(sproutling.attack())
    print(sproutling.heal())
    print(" evolved:")
    bloomelle = HealingCreatureFactory().create_evolved()
    print(bloomelle.describe())
    print(bloomelle.attack())
    print(bloomelle.heal())
    print("\nTesting Creature with transform capability")
    print(" base:")
    shiftling = TransformCreatureFactory().create_base()
    print(shiftling.describe())
    print(shiftling.attack())
    print(shiftling.transform())
    print(shiftling.attack())
    print(shiftling.revert())
    print(" evolved:")
    morphogon = TransformCreatureFactory().create_evolved()
    print(morphogon.describe())
    print(morphogon.attack())
    print(morphogon.transform())
    print(morphogon.attack())
    print(morphogon.revert())
